# Generated by Django 5.1 on 2024-09-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='photo',
            field=models.ImageField(default='/static/images/done.jpg', upload_to='image'),
        ),
    ]
